name: "Slack Alert"
description: "Send an alert to a Slack channel on a failed build"


inputs:
  authorText:
    description: "The name of the commit author and link"
  commitText:
    description: "The commit SHA and link to it"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # ratchet:actions/github-script@v7
      id: build_message
      with:
        script: |
          console.log("text is" , ${{ inputs.authorText }});
          core.setOutput('popop', ${{ inputs.authorText }});
    - name: echo
      shell: bash
      run: |
        echo "here you go " ${{ steps.build_message.outputs.popop }}
