name: aftermerge

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "aftermerge"
  cancel-in-progress: false

jobs:
  run1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Update tag
        uses: actions/github-script@v7
        with:
          # https://docs.github.com/en/rest/git/refs#update-a-reference
          # You can find all of our tag refs here: https://github.com/Cinemo-GmbH/pace/tags
          # Don't get them confused with git tags. As you cannot find them using "git" they are different.
          # You can add a ref for a specific commit using the GitHub CLI "gh".
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/tags/dev',
              sha: context.sha
            })
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
          steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Triage Workflow
        run: |
          gh workflow run Second.yml --ref tags/dev
        env:
          GITHUB_TOKEN: ${{ secrets.GG_TOKEN }}