name: aftermerge

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "aftermerge"
  cancel-in-progress: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
  deploy:
    needs: [prepare]
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
