name: aftermerge

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "aftermerge"
  cancel-in-progress: false

jobs:
  run1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
          steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Triage Workflow
        run: |
          gh workflow run afterMerge.yml --ref ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GG_TOKEN }}