name: aftermerge

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "aftermerge"
  cancel-in-progress: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
  run1:
    needs: [prepare]
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
          steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install gh CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
      - name: Run Triage Workflow
        run: |
          gh workflow run afterMerge.yml --ref github.sha