name: Control Deployments
run-name: ${{ github.event.inputs.control }} deploy to ${{ github.event.inputs.environment }} by ${{ github.event.author.name }}

on:
  workflow_dispatch:
    inputs:
      control:
        type: choice
        description: enable or disable deployment
        required: true
        options:
          - "Enable"
          - "Disable"
      environment:
        type: choice
        description: environment to control
        required: true
        options:
          - "Development"
          - "Production"
jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          if [[ "${{ github.event.inputs.control }}" == "Disable" && "${{ github.event.inputs.environment }}" == "Development" ]]; then
            gh variable set LOCK_DEVELOPMENT_DEPLOYMENT --body "true"
          fi
          
          if [[ "${{ github.event.inputs.control }}" == "Disable" && "${{ github.event.inputs.environment }}" == "Production" ]]; then
            gh variable set LOCK_DEVELOPMENT_PRODUCTION --body "true"
          fi
          
          if [[ "${{ github.event.inputs.control }}" == "Enable" && "${{ github.event.inputs.environment }}" == "Development" ]]; then
            gh variable set LOCK_DEVELOPMENT_DEPLOYMENT --body "false"
          fi
          
          if [[ "${{ github.event.inputs.control }}" == "Enable" && "${{ github.event.inputs.environment }}" == "Production" ]]; then
            gh variable set LOCK_DEVELOPMENT_PRODUCTION --body "false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GG_TOKEN }}

