name: Secoond

on:
  workflow_run:
    workflows: ["aftermerge"]
    types:
      - completed

jobs:
  dance:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "before github ref"
          echo ${{ github.sha }}
      - name: Checkout my_organization/my_private_repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "previous branch"
          echo ${{ github.event.workflow_run.head_sha }}
          echo "current ref"
          echo ${{ github.sha }}

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
