name: Secoond

on:
  workflow_run:
    workflows: ["aftermerge"]
    types:
      - completed

jobs:
  dance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my_organization/my_private_repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
